version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
    # allow docker to access db on port 5432 and also outlise docker with 5432
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: pass123